### ISSUE TITLE
Incorrect answer for question 108 in GitHub Actions

### ISSUE THREAD

**Issue by StuartvdLee** [FidelusAleksander/ghcertified#265]
In question 108 under GitHub Actions, the correct answer states:

```yaml
on:
    check_run:
        types: [requested, completed]
```

However, the [GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#check_run) do not include the `requested` type, but rather the `rerequested` type.
